# Generated by Django 4.2.16 on 2024-11-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='img',
            field=models.ImageField(default=None, upload_to='photousers/', verbose_name='Фото'),
        ),
    ]
