# Generated by Django 4.2.16 on 2024-12-04 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_users_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caetegory_drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=200, verbose_name='емаил'),
        ),
        migrations.AlterField(
            model_name='users',
            name='family',
            field=models.CharField(max_length=200, verbose_name='фамилия'),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=200, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=200, verbose_name='пароль'),
        ),
        migrations.AlterField(
            model_name='users',
            name='status',
            field=models.CharField(max_length=200, verbose_name='статус'),
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('article', models.CharField(max_length=2000, verbose_name='Описание')),
                ('img', models.ImageField(default=None, upload_to='drug/', verbose_name='Фото')),
                ('price', models.IntegerField(max_length=200, verbose_name='цена')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('editdate', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('caetegory_drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.caetegory_drug')),
            ],
        ),
        migrations.CreateModel(
            name='Dorixona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('article', models.CharField(max_length=200, verbose_name='Описание')),
                ('email', models.CharField(max_length=200, verbose_name='емаил')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('editdate', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.users')),
            ],
        ),
    ]
