# Generated by Django 4.2.16 on 2024-12-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_caetegory_drug_alter_users_email_alter_users_family_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='img',
            field=models.FileField(default=None, upload_to='upl/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='users',
            name='img',
            field=models.FileField(default=None, upload_to='upl/', verbose_name='Фото'),
        ),
    ]
