# Generated by Django 4.2.16 on 2024-12-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_drug_img_alter_users_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='price',
            field=models.IntegerField(verbose_name='цена'),
        ),
    ]
