# Generated by Django 4.2.16 on 2024-12-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_drug_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dorixona',
            name='article',
            field=models.TextField(max_length=20000, verbose_name='Описание'),
        ),
    ]
