# Generated by Django 4.2.16 on 2024-12-12 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_dorixona_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='caetegory_dorixona',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='main.dorixona'),
        ),
    ]
