# Generated by Django 4.2.16 on 2024-12-12 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_drug_caetegory_dorixona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='caetegory_dorixona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dorixona'),
        ),
    ]
