# Generated by Django 4.2.16 on 2024-12-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_drug_caetegory_dorixona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='img',
            field=models.FileField(upload_to='upl/', verbose_name='Фото'),
        ),
    ]
