# Generated by Django 4.2.16 on 2024-12-15 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_drug_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drug',
            old_name='caetegory_dorixona',
            new_name='caetegorydorixona',
        ),
        migrations.RenameField(
            model_name='drug',
            old_name='caetegory_drug',
            new_name='caetegorydrug',
        ),
    ]
