# Generated by Django 4.2.16 on 2024-12-23 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_commentdrug'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentdrug',
            name='comudrug',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.drug'),
            preserve_default=False,
        ),
    ]
