# Generated by Django 4.2.16 on 2024-12-24 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_commentdrug_comudrug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('img', models.FileField(upload_to='upl/', verbose_name='Фото')),
                ('price', models.IntegerField(verbose_name='цена')),
                ('quantity', models.IntegerField(verbose_name='количество')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.drug')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.users')),
            ],
        ),
    ]
