# Generated by Django 4.2.16 on 2025-01-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='drug',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='user',
            field=models.IntegerField(),
        ),
    ]
