# Generated by Django 4.2.16 on 2025-01-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_card_drug_alter_card_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('img', models.FileField(upload_to='upl/', verbose_name='Фото')),
                ('price', models.IntegerField(verbose_name='цена')),
                ('quantity', models.IntegerField(verbose_name='количество')),
                ('total', models.IntegerField(verbose_name='количество')),
                ('user_id', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='card',
            old_name='drug',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='card',
            name='user',
        ),
    ]
