# Generated by Django 4.2.16 on 2025-01-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_check_rename_drug_card_user_id_remove_card_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='total',
            field=models.IntegerField(verbose_name='итого'),
        ),
    ]
