# Generated by Django 4.2.16 on 2025-01-08 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_check_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='drug',
            field=models.CharField(default=1, max_length=200, verbose_name='лекарства'),
            preserve_default=False,
        ),
    ]
