# Generated by Django 4.2.16 on 2025-01-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_check_drug'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='drug',
            field=models.IntegerField(default=1, verbose_name='коли'),
            preserve_default=False,
        ),
    ]
